//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooncakeTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseThread
    {
        public int Id { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<decimal> WeightImpact { get; set; }
        public string TechCategory { get; set; }
        public string IssueType { get; set; }
        public string ThreadTitle { get; set; }
        public string ThreadUrl { get; set; }
        public Nullable<decimal> AvgPageView { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> Replies { get; set; }
        public Nullable<int> UniquePoster { get; set; }
        public Nullable<int> Subscriber { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<decimal> IRT { get; set; }
        public Nullable<System.DateTime> LastReply { get; set; }
        public Nullable<bool> Answered { get; set; }
        public string AnsweredBy { get; set; }
        public string ThreadType { get; set; }
        public string Trend { get; set; }
        public string TrendUrl { get; set; }
        public string CSSDone { get; set; }
        public string CustomerNeeded { get; set; }
        public string Difficult { get; set; }
    }
}
