//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooncakeTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeState
    {
        public int Id { get; set; }
        public string State { get; set; }
        public string Style { get; set; }
        public string Width { get; set; }
        public Nullable<int> Num { get; set; }
    }
}
