//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooncakeTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class GitHubIssue
    {
        public int Id { get; set; }
        public Nullable<int> GitCodeId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string IssueUser { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string State { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> CloseAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string Html_Url { get; set; }
    
        public virtual SampleCode SampleCode { get; set; }
    }
}
