//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooncakeTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public string HistoryType { get; set; }
        public Nullable<int> ForeignId { get; set; }
        public Nullable<bool> IsHistory { get; set; }
        public Nullable<int> GitCodeId { get; set; }
    }
}
