//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooncakeTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleCode
    {
        public SampleCode()
        {
            this.CodeOperations = new HashSet<CodeOperation>();
            this.GitHubCommits = new HashSet<GitHubCommit>();
            this.GitHubIssues = new HashSet<GitHubIssue>();
            this.GitHubPullRequests = new HashSet<GitHubPullRequest>();
            this.Histories = new HashSet<History>();
            this.SamplePlatforms = new HashSet<SamplePlatform>();
            this.SampleProducts = new HashSet<SampleProduct>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string GitResourceUrl { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> CustomAt { get; set; }
    
        public virtual ICollection<CodeOperation> CodeOperations { get; set; }
        public virtual ICollection<GitHubCommit> GitHubCommits { get; set; }
        public virtual ICollection<GitHubIssue> GitHubIssues { get; set; }
        public virtual ICollection<GitHubPullRequest> GitHubPullRequests { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<SamplePlatform> SamplePlatforms { get; set; }
        public virtual ICollection<SampleProduct> SampleProducts { get; set; }
    }
}
